# Generated by Django 4.0.4 on 2024-05-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='biz_name',
        ),
    ]
